-- GENERATED by scripts/chain-contract-fixture.ts. Do not hand-edit.
-- The application test verifies this exact file against chainSavings(); pgTAP
-- then submits the generated values to the real database constraints.
begin;

create extension if not exists pgtap with schema extensions;
set local search_path = extensions, public, pg_catalog;

select plan(4);

select lives_ok(
  $$ update public.savings_periods
     set baseline_amount = 1000000,
         opening_amount = 900000,
         final_amount = 900000,
         cost_reduction_amount = 100000,
         cost_avoidance_amount = -100000,
         total_savings_amount = 0,
         executed_baseline_amount = 1000000,
         executed_opening_amount = 900000,
         executed_final_amount = 900000,
         executed_cost_reduction_amount = 100000,
         executed_cost_avoidance_amount = -100000,
         executed_total_savings_amount = 0
     where id = '00000000-0000-4000-8000-000000000061' $$,
  'the database accepts the TypeScript-generated signed period chain'
);

select is(
  (select array[cost_reduction_amount, cost_avoidance_amount, total_savings_amount]
   from public.savings_periods
   where id = '00000000-0000-4000-8000-000000000061'),
  array[100000, -100000, 0]::numeric[],
  'the stored period legs equal the TypeScript fixture verbatim'
);

select lives_ok(
  $$ update public.savings_calculations
     set baseline_total_amount = 3000000,
         opening_proposal_amount = 2700000,
         award_total_amount = 2700000,
         cost_reduction_amount = 300000,
         cost_avoidance_amount = -300000,
         gross_savings_amount = 0,
         net_savings_amount = 0
     where id = '00000000-0000-4000-8000-000000000051' $$,
  'the database accepts the TypeScript-generated signed calculation chain'
);

select is(
  (select array[cost_reduction_amount, cost_avoidance_amount, gross_savings_amount]
   from public.savings_calculations
   where id = '00000000-0000-4000-8000-000000000051'),
  array[300000, -300000, 0]::numeric[],
  'the stored calculation legs equal the TypeScript fixture verbatim'
);

select * from finish();
rollback;
