-- =====================================================================
-- P8: PROFESSIONAL SERVICES SCENARIOS
-- =====================================================================
-- Two projects that exercise the shapes consulting work actually takes,
-- neither of which is a whole number of years:
--
--   * a FOUR-MONTH implementation project - shorter than a single annual
--     period. The Annual schedule must produce one period that books four
--     months. Booking a full year here would invent savings that the
--     contract cannot produce.
--
--   * an EIGHTEEN-MONTH consulting contract - one and a half years. The
--     Annual schedule must run 12 months plus a 6-month stub, and because
--     it starts in September it straddles THREE calendar years, so the
--     monthly schedule is what gives an honest fiscal-year split.
--
-- Additive: inserts only, on conflict do nothing. Nothing existing is
-- touched, so this can be run on top of P6 safely and more than once.
--
-- Every figure below was COMPUTED by the same chain the app uses, on the
-- whole-term basis. Generated by scratchpad/gen_prof_services.py, and the
-- same numbers are asserted by `npm run verify` (sections 9 and 10).
--
-- Requires P7 for the schedule; the schedules themselves are generated in
-- the app, on the Schedule tab, not seeded here.
-- =====================================================================

begin;

-- Projects
insert into public.sourcing_events (id, organization_id, event_name, event_description, event_type,
  category_id, business_unit_id, awarded_supplier_id, procurement_owner_id, event_status,
  currency_code, fx_rate_to_usd, event_start_date, contract_start_date, contract_end_date,
  project_type, buyer_name, created_at, created_by, updated_at, updated_by) values
  ('00000021-0000-4000-8000-000000000009', '27a0b547-c58b-4404-b2e9-cf5bb40893d6', 'ERP Implementation Consulting', 'A FOUR-MONTH professional services project. Net new work, so there is no baseline: the whole span books as Cost Avoidance and Cost Reduction reads n/a. The term is shorter than a single annual period, so an Annual schedule produces one period that books four months - never a full year.', 'Net New Purchase', '000000c1-0000-4000-8000-000000000004', '000000b1-0000-4000-8000-000000000001', '00000051-0000-4000-8000-000000000004', 'c9b10017-4a74-479f-a908-c8bc91885d44', 'Contracted', 'USD', 1, '2026-03-01', '2026-03-01', '2026-06-30', 'Sourcing', 'Sample Buyer', now(), 'c9b10017-4a74-479f-a908-c8bc91885d44', now(), 'c9b10017-4a74-479f-a908-c8bc91885d44'),
  ('00000021-0000-4000-8000-000000000010', '27a0b547-c58b-4404-b2e9-cf5bb40893d6', 'Managed Services Consulting - 18 Month', 'AN EIGHTEEN-MONTH consulting contract - one and a half years. A 12-month baseline is compared against an 18-month final offer, and an Annual schedule runs 12 months plus a 6-month stub rather than rounding up to two full years. Starting in September it straddles three calendar years, which is what makes it the useful fiscal-year test.', 'Net New Purchase', '000000c1-0000-4000-8000-000000000004', '000000b1-0000-4000-8000-000000000003', '00000051-0000-4000-8000-000000000004', 'c9b10017-4a74-479f-a908-c8bc91885d44', 'Contracted', 'USD', 1, '2026-09-01', '2026-09-01', '2028-02-29', 'Sourcing', 'Sample Buyer', now(), 'c9b10017-4a74-479f-a908-c8bc91885d44', now(), 'c9b10017-4a74-479f-a908-c8bc91885d44')
on conflict (id) do nothing;

-- Baselines. Only the 18-month renewal has one; the 4-month project is net new.
insert into public.baselines (id, organization_id, event_id, baseline_name, baseline_type,
  baseline_source, baseline_total_amount, baseline_term_months, is_selected,
  baseline_lock_status, official_for_hard_savings, official_for_cost_avoidance,
  official_for_demand_reduction, created_at, created_by, updated_at, updated_by) values
  ('00000041-0000-4000-8000-000000000010', '27a0b547-c58b-4404-b2e9-cf5bb40893d6', '00000021-0000-4000-8000-000000000010', 'Prior 12-Month Actual - AP spend by vendor', 'Prior 12-Month Actual', 'AP spend by vendor', 600000, 12, true, 'Draft', true, true, true, now(), 'c9b10017-4a74-479f-a908-c8bc91885d44', now(), 'c9b10017-4a74-479f-a908-c8bc91885d44')
on conflict (id) do nothing;

-- Supplier offers. offer_role marks the Opening and the Final in the chain.
insert into public.supplier_offers (id, organization_id, event_id, supplier_id, offer_type,
  offer_round, offer_date, offer_currency_code, fx_rate_to_usd, offer_total_amount,
  offer_term_months, offer_role, compliant_bid_flag, selected_for_award_flag,
  created_at, created_by, updated_at, updated_by) values
  ('00000061-0000-4000-8000-000000000015', '27a0b547-c58b-4404-b2e9-cf5bb40893d6', '00000021-0000-4000-8000-000000000009', '00000051-0000-4000-8000-000000000004', 'Initial', 1, '2026-03-01', 'USD', 1, 130000, 4, 'opening', true, false, now(), 'c9b10017-4a74-479f-a908-c8bc91885d44', now(), 'c9b10017-4a74-479f-a908-c8bc91885d44'),
  ('00000061-0000-4000-8000-000000000016', '27a0b547-c58b-4404-b2e9-cf5bb40893d6', '00000021-0000-4000-8000-000000000009', '00000051-0000-4000-8000-000000000004', 'Best and Final (BAFO)', 2, '2026-03-01', 'USD', 1, 100000, 4, 'final', true, true, now(), 'c9b10017-4a74-479f-a908-c8bc91885d44', now(), 'c9b10017-4a74-479f-a908-c8bc91885d44'),
  ('00000061-0000-4000-8000-000000000017', '27a0b547-c58b-4404-b2e9-cf5bb40893d6', '00000021-0000-4000-8000-000000000010', '00000051-0000-4000-8000-000000000004', 'Initial', 1, '2026-09-01', 'USD', 1, 1000000, 18, 'opening', true, false, now(), 'c9b10017-4a74-479f-a908-c8bc91885d44', now(), 'c9b10017-4a74-479f-a908-c8bc91885d44'),
  ('00000061-0000-4000-8000-000000000018', '27a0b547-c58b-4404-b2e9-cf5bb40893d6', '00000021-0000-4000-8000-000000000010', '00000051-0000-4000-8000-000000000004', 'Best and Final (BAFO)', 2, '2026-09-01', 'USD', 1, 810000, 18, 'final', true, true, now(), 'c9b10017-4a74-479f-a908-c8bc91885d44', now(), 'c9b10017-4a74-479f-a908-c8bc91885d44')
on conflict (id) do nothing;

-- Savings calculations, DERIVED (whole-term basis) by the same chain the app uses.
insert into public.savings_calculations (id, organization_id, event_id, baseline_id,
  calculation_name, savings_type, baseline_total_amount, opening_proposal_amount,
  award_total_amount, gross_savings_amount, savings_percentage, net_savings_amount,
  cost_reduction_amount, cost_avoidance_amount, calculation_status, recognition_notes,
  savings_start_date, savings_end_date, created_at, created_by, updated_at, updated_by) values
  ('000000a1-0000-4000-8000-000000000009', '27a0b547-c58b-4404-b2e9-cf5bb40893d6', '00000021-0000-4000-8000-000000000009', null, '4-month deal savings', 'Cost Avoidance', null, 130000, 100000, 30000, 23.08, 30000, null, 30000, 'contracted', 'Derived from the selected anchors over the 4-month deal term.', '2026-03-01', '2026-06-30', now(), 'c9b10017-4a74-479f-a908-c8bc91885d44', now(), 'c9b10017-4a74-479f-a908-c8bc91885d44'),
  ('000000a1-0000-4000-8000-000000000010', '27a0b547-c58b-4404-b2e9-cf5bb40893d6', '00000021-0000-4000-8000-000000000010', '00000041-0000-4000-8000-000000000010', '18-month deal savings', 'Cost Avoidance', 900000, 1000000, 810000, 190000, 21.11, 190000, 90000, 100000, 'contracted', 'Derived from the selected anchors over the 18-month deal term.', '2026-09-01', '2028-02-29', now(), 'c9b10017-4a74-479f-a908-c8bc91885d44', now(), 'c9b10017-4a74-479f-a908-c8bc91885d44')
on conflict (id) do nothing;

commit;

-- ---------------------------------------------------------------------
-- WHAT TO EXPECT IN THE APP (all three period types book the same total)
-- ---------------------------------------------------------------------
--   ERP Implementation Consulting (4 months, 2026-03-01 to 2026-06-30)
--     baseline null  opening 130000  final 100000
--     reduction null  avoidance 30000  total 30000
--     monthly   4 period(s), months per period [1, 1, 1, 1]
--     annual    1 period(s), months per period [4]
--     one_time  1 period(s), months per period [4]
--
--   Managed Services Consulting - 18 Month (18 months, 2026-09-01 to 2028-02-29)
--     baseline 900000  opening 1000000  final 810000
--     reduction 90000  avoidance 100000  total 190000
--     monthly   18 period(s), months per period [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
--     annual    2 period(s), months per period [12, 6]
--     one_time  1 period(s), months per period [18]
--