-- =====================================================================
-- P6: SHOWCASE DATA
-- =====================================================================
-- Eight projects chosen to exercise every behaviour the app now has:
--   * a 12-month baseline vs a 36-month final (term normalisation)
--   * a straightforward hard reduction
--   * a NET INCREASE - negative reduction, shown in parentheses
--   * NO BASELINE - whole span books as avoidance, reduction is n/a
--   * NO OPENING - total collapses to reduction
--   * an IN-FLIGHT deal - reports as forecast, not booked
--   * a 5-year term with the escalator priced into the offer
--   * a SUPPORT project with no savings at all
--
-- Every savings figure below was COMPUTED by the same chain the app uses,
-- on the whole-term basis, so the seeded rows agree with what the
-- Calculations tab derives. Generated by scratchpad/gen_showcase.py.
-- =====================================================================

begin;

-- Clear transactional data only. Org, profile and existing dimensions stay.
truncate table
  public.realization_periods, public.savings_calculation_lines, public.savings_calculations,
  public.award_lines, public.awards, public.supplier_offer_lines, public.supplier_offers,
  public.baseline_lines, public.baselines, public.event_scope_lines, public.sourcing_events
  restart identity cascade;

-- Dimensions (idempotent - skipped if already present).
insert into public.business_units (id, organization_id, business_unit_name, active_flag, created_at) values
  ('000000b1-0000-4000-8000-000000000001', '27a0b547-c58b-4404-b2e9-cf5bb40893d6', 'IT & Digital', true, now()),
  ('000000b1-0000-4000-8000-000000000002', '27a0b547-c58b-4404-b2e9-cf5bb40893d6', 'Operations', true, now()),
  ('000000b1-0000-4000-8000-000000000003', '27a0b547-c58b-4404-b2e9-cf5bb40893d6', 'Corporate Services', true, now()),
  ('000000b1-0000-4000-8000-000000000004', '27a0b547-c58b-4404-b2e9-cf5bb40893d6', 'Manufacturing', true, now())
on conflict (id) do nothing;

insert into public.categories (id, organization_id, category_name, default_baseline_type, created_at) values
  ('000000c1-0000-4000-8000-000000000001', '27a0b547-c58b-4404-b2e9-cf5bb40893d6', 'IT Software', 'Current Contract', now()),
  ('000000c1-0000-4000-8000-000000000002', '27a0b547-c58b-4404-b2e9-cf5bb40893d6', 'Logistics', 'Current Contract', now()),
  ('000000c1-0000-4000-8000-000000000003', '27a0b547-c58b-4404-b2e9-cf5bb40893d6', 'Facilities', 'Current Contract', now()),
  ('000000c1-0000-4000-8000-000000000004', '27a0b547-c58b-4404-b2e9-cf5bb40893d6', 'Professional Services', 'Current Contract', now()),
  ('000000c1-0000-4000-8000-000000000005', '27a0b547-c58b-4404-b2e9-cf5bb40893d6', 'Marketing', 'Current Contract', now()),
  ('000000c1-0000-4000-8000-000000000006', '27a0b547-c58b-4404-b2e9-cf5bb40893d6', 'MRO', 'Current Contract', now())
on conflict (id) do nothing;

insert into public.suppliers (id, organization_id, supplier_name, supplier_normalized_name, supplier_status, created_at, updated_at) values
  ('00000051-0000-4000-8000-000000000001', '27a0b547-c58b-4404-b2e9-cf5bb40893d6', 'Northwind Systems', 'northwind systems', 'Active', now(), now()),
  ('00000051-0000-4000-8000-000000000002', '27a0b547-c58b-4404-b2e9-cf5bb40893d6', 'Vertex Logistics', 'vertex logistics', 'Active', now(), now()),
  ('00000051-0000-4000-8000-000000000003', '27a0b547-c58b-4404-b2e9-cf5bb40893d6', 'Harbor Facilities Group', 'harbor facilities group', 'Active', now(), now()),
  ('00000051-0000-4000-8000-000000000004', '27a0b547-c58b-4404-b2e9-cf5bb40893d6', 'Lumen Advisory', 'lumen advisory', 'Active', now(), now()),
  ('00000051-0000-4000-8000-000000000005', '27a0b547-c58b-4404-b2e9-cf5bb40893d6', 'Brightline Media', 'brightline media', 'Active', now(), now()),
  ('00000051-0000-4000-8000-000000000006', '27a0b547-c58b-4404-b2e9-cf5bb40893d6', 'Irongate Industrial', 'irongate industrial', 'Active', now(), now()),
  ('00000051-0000-4000-8000-000000000007', '27a0b547-c58b-4404-b2e9-cf5bb40893d6', 'Cobalt Software', 'cobalt software', 'Active', now(), now()),
  ('00000051-0000-4000-8000-000000000008', '27a0b547-c58b-4404-b2e9-cf5bb40893d6', 'Meridian Networks', 'meridian networks', 'Active', now(), now())
on conflict (id) do nothing;

-- Projects
insert into public.sourcing_events (id, organization_id, event_name, event_description, event_type,
  category_id, business_unit_id, awarded_supplier_id, procurement_owner_id, event_status,
  currency_code, fx_rate_to_usd, event_start_date, contract_start_date, contract_end_date,
  project_type, buyer_name, notes, created_at, created_by, updated_at, updated_by) values
  ('00000021-0000-4000-8000-000000000001', '27a0b547-c58b-4404-b2e9-cf5bb40893d6', 'ERP Platform Renewal', 'Three-year renewal. Vendor opened above current spend; landed well below it. Shows a 12-month baseline compared against a 36-month final offer.', 'Renewal', '000000c1-0000-4000-8000-000000000001', '000000b1-0000-4000-8000-000000000001', '00000051-0000-4000-8000-000000000001', 'c9b10017-4a74-479f-a908-c8bc91885d44', 'Contracted', 'USD', 1, '2026-01-01', '2026-01-01', '2028-12-31', 'Sourcing', 'Sample Buyer', null, now(), 'c9b10017-4a74-479f-a908-c8bc91885d44', now(), 'c9b10017-4a74-479f-a908-c8bc91885d44'),
  ('00000021-0000-4000-8000-000000000002', '27a0b547-c58b-4404-b2e9-cf5bb40893d6', 'Freight Carrier Rebid', 'Competitive rebid across four carriers. A straightforward hard reduction against last year''s actual spend.', 'Renewal', '000000c1-0000-4000-8000-000000000002', '000000b1-0000-4000-8000-000000000002', '00000051-0000-4000-8000-000000000002', 'c9b10017-4a74-479f-a908-c8bc91885d44', 'Realized', 'USD', 1, '2025-10-01', '2025-10-01', '2026-09-30', 'Sourcing', 'Sample Buyer', null, now(), 'c9b10017-4a74-479f-a908-c8bc91885d44', now(), 'c9b10017-4a74-479f-a908-c8bc91885d44'),
  ('00000021-0000-4000-8000-000000000003', '27a0b547-c58b-4404-b2e9-cf5bb40893d6', 'Facilities Services Renewal', 'A NET INCREASE. The renewal costs more than today, but far less than the vendor asked for. Cost Reduction is negative and shown in parentheses; it is never relabelled as savings.', 'Renewal', '000000c1-0000-4000-8000-000000000003', '000000b1-0000-4000-8000-000000000003', '00000051-0000-4000-8000-000000000003', 'c9b10017-4a74-479f-a908-c8bc91885d44', 'Contracted', 'USD', 1, '2026-03-01', '2026-03-01', '2027-02-28', 'Sourcing', 'Sample Buyer', null, now(), 'c9b10017-4a74-479f-a908-c8bc91885d44', now(), 'c9b10017-4a74-479f-a908-c8bc91885d44'),
  ('00000021-0000-4000-8000-000000000004', '27a0b547-c58b-4404-b2e9-cf5bb40893d6', 'Lab Instrumentation - Net New', 'NO BASELINE. A first-time purchase with no incumbent spend, so the whole span books as Cost Avoidance and Cost Reduction reads ''n/a'' - which is a distinct state from zero.', 'Renewal', '000000c1-0000-4000-8000-000000000004', '000000b1-0000-4000-8000-000000000004', '00000051-0000-4000-8000-000000000006', 'c9b10017-4a74-479f-a908-c8bc91885d44', 'Contracted', 'USD', 1, '2026-05-01', '2026-05-01', '2027-04-30', 'Sourcing', 'Sample Buyer', null, now(), 'c9b10017-4a74-479f-a908-c8bc91885d44', now(), 'c9b10017-4a74-479f-a908-c8bc91885d44'),
  ('00000021-0000-4000-8000-000000000005', '27a0b547-c58b-4404-b2e9-cf5bb40893d6', 'MRO Consumables Consolidation', 'NO OPENING PROPOSAL captured (consolidation, not a negotiation), so the total collapses to Cost Reduction.', 'Renewal', '000000c1-0000-4000-8000-000000000006', '000000b1-0000-4000-8000-000000000002', '00000051-0000-4000-8000-000000000006', 'c9b10017-4a74-479f-a908-c8bc91885d44', 'Contracted', 'USD', 1, '2026-02-01', '2026-02-01', '2027-01-31', 'Sourcing', 'Sample Buyer', null, now(), 'c9b10017-4a74-479f-a908-c8bc91885d44', now(), 'c9b10017-4a74-479f-a908-c8bc91885d44'),
  ('00000021-0000-4000-8000-000000000006', '27a0b547-c58b-4404-b2e9-cf5bb40893d6', 'Marketing Agency Retainer', 'IN FLIGHT. Not yet signed, so this reports as FORECAST rather than booked savings on the dashboard.', 'Renewal', '000000c1-0000-4000-8000-000000000005', '000000b1-0000-4000-8000-000000000003', '00000051-0000-4000-8000-000000000005', 'c9b10017-4a74-479f-a908-c8bc91885d44', 'Negotiation', 'USD', 1, '2026-09-01', '2026-09-01', '2027-08-31', 'Sourcing', 'Sample Buyer', null, now(), 'c9b10017-4a74-479f-a908-c8bc91885d44', now(), 'c9b10017-4a74-479f-a908-c8bc91885d44'),
  ('00000021-0000-4000-8000-000000000007', '27a0b547-c58b-4404-b2e9-cf5bb40893d6', 'Network Infrastructure - 5 Year', 'A FIVE-YEAR term with the annual escalator priced into the offer totals, which is why a single amount plus a term stays exact.', 'Renewal', '000000c1-0000-4000-8000-000000000001', '000000b1-0000-4000-8000-000000000001', '00000051-0000-4000-8000-000000000008', 'c9b10017-4a74-479f-a908-c8bc91885d44', 'Contracted', 'USD', 1, '2026-04-01', '2026-04-01', '2031-03-31', 'Sourcing', 'Sample Buyer', null, now(), 'c9b10017-4a74-479f-a908-c8bc91885d44', now(), 'c9b10017-4a74-479f-a908-c8bc91885d44'),
  ('00000021-0000-4000-8000-000000000008', '27a0b547-c58b-4404-b2e9-cf5bb40893d6', 'Contract Review - Legal Question', 'A SUPPORT project: non-commercial work with no savings attached. Shows the support path, which hides the money screens entirely.', 'Contract Question', null, '000000b1-0000-4000-8000-000000000003', null, 'c9b10017-4a74-479f-a908-c8bc91885d44', 'In Progress', 'USD', 1, null, null, null, 'Support', 'Sample Buyer', null, now(), 'c9b10017-4a74-479f-a908-c8bc91885d44', now(), 'c9b10017-4a74-479f-a908-c8bc91885d44');

-- Baselines. is_selected marks the one the chain measures against.
insert into public.baselines (id, organization_id, event_id, baseline_name, baseline_type,
  baseline_source, baseline_total_amount, baseline_term_months, is_selected,
  baseline_lock_status, official_for_hard_savings, official_for_cost_avoidance,
  official_for_demand_reduction, created_at, created_by, updated_at, updated_by) values
  ('00000041-0000-4000-8000-000000000001', '27a0b547-c58b-4404-b2e9-cf5bb40893d6', '00000021-0000-4000-8000-000000000001', 'Prior 12-Month Actual - ERP export', 'Prior 12-Month Actual', 'ERP export', 1000000, 12, true, 'Draft', true, true, true, now(), 'c9b10017-4a74-479f-a908-c8bc91885d44', now(), 'c9b10017-4a74-479f-a908-c8bc91885d44'),
  ('00000041-0000-4000-8000-000000000002', '27a0b547-c58b-4404-b2e9-cf5bb40893d6', '00000021-0000-4000-8000-000000000002', 'Prior 12-Month Actual - Carrier invoices', 'Prior 12-Month Actual', 'Carrier invoices', 4500000, 12, true, 'Draft', true, true, true, now(), 'c9b10017-4a74-479f-a908-c8bc91885d44', now(), 'c9b10017-4a74-479f-a908-c8bc91885d44'),
  ('00000041-0000-4000-8000-000000000003', '27a0b547-c58b-4404-b2e9-cf5bb40893d6', '00000021-0000-4000-8000-000000000003', 'Current Contract - Signed agreement', 'Current Contract', 'Signed agreement', 800000, 12, true, 'Draft', true, true, true, now(), 'c9b10017-4a74-479f-a908-c8bc91885d44', now(), 'c9b10017-4a74-479f-a908-c8bc91885d44'),
  ('00000041-0000-4000-8000-000000000005', '27a0b547-c58b-4404-b2e9-cf5bb40893d6', '00000021-0000-4000-8000-000000000005', 'Prior 12-Month Actual - Spend cube', 'Prior 12-Month Actual', 'Spend cube', 600000, 12, true, 'Draft', true, true, true, now(), 'c9b10017-4a74-479f-a908-c8bc91885d44', now(), 'c9b10017-4a74-479f-a908-c8bc91885d44'),
  ('00000041-0000-4000-8000-000000000006', '27a0b547-c58b-4404-b2e9-cf5bb40893d6', '00000021-0000-4000-8000-000000000006', 'Current Contract - Master services agreement', 'Current Contract', 'Master services agreement', 1200000, 12, true, 'Draft', true, true, true, now(), 'c9b10017-4a74-479f-a908-c8bc91885d44', now(), 'c9b10017-4a74-479f-a908-c8bc91885d44'),
  ('00000041-0000-4000-8000-000000000007', '27a0b547-c58b-4404-b2e9-cf5bb40893d6', '00000021-0000-4000-8000-000000000007', 'Should-Cost Model - Build-up from unit rates', 'Should-Cost Model', 'Build-up from unit rates', 2000000, 12, true, 'Draft', true, true, true, now(), 'c9b10017-4a74-479f-a908-c8bc91885d44', now(), 'c9b10017-4a74-479f-a908-c8bc91885d44');

-- Supplier offers. offer_role marks the Opening and the Final in the chain;
-- marking an offer 'final' is the award decision.
insert into public.supplier_offers (id, organization_id, event_id, supplier_id, offer_type,
  offer_round, offer_date, offer_currency_code, fx_rate_to_usd, offer_total_amount,
  offer_term_months, offer_role, compliant_bid_flag, selected_for_award_flag,
  created_at, created_by, updated_at, updated_by) values
  ('00000061-0000-4000-8000-000000000001', '27a0b547-c58b-4404-b2e9-cf5bb40893d6', '00000021-0000-4000-8000-000000000001', '00000051-0000-4000-8000-000000000001', 'Initial', 1, '2026-01-01', 'USD', 1, 1200000, 12, 'opening', true, false, now(), 'c9b10017-4a74-479f-a908-c8bc91885d44', now(), 'c9b10017-4a74-479f-a908-c8bc91885d44'),
  ('00000061-0000-4000-8000-000000000002', '27a0b547-c58b-4404-b2e9-cf5bb40893d6', '00000021-0000-4000-8000-000000000001', '00000051-0000-4000-8000-000000000001', 'Revised', 2, '2026-01-01', 'USD', 1, 3100000, 36, null, true, false, now(), 'c9b10017-4a74-479f-a908-c8bc91885d44', now(), 'c9b10017-4a74-479f-a908-c8bc91885d44'),
  ('00000061-0000-4000-8000-000000000003', '27a0b547-c58b-4404-b2e9-cf5bb40893d6', '00000021-0000-4000-8000-000000000001', '00000051-0000-4000-8000-000000000001', 'Best and Final (BAFO)', 3, '2026-01-01', 'USD', 1, 2700000, 36, 'final', true, true, now(), 'c9b10017-4a74-479f-a908-c8bc91885d44', now(), 'c9b10017-4a74-479f-a908-c8bc91885d44'),
  ('00000061-0000-4000-8000-000000000004', '27a0b547-c58b-4404-b2e9-cf5bb40893d6', '00000021-0000-4000-8000-000000000002', '00000051-0000-4000-8000-000000000002', 'Initial', 1, '2025-10-01', 'USD', 1, 4800000, 12, 'opening', true, false, now(), 'c9b10017-4a74-479f-a908-c8bc91885d44', now(), 'c9b10017-4a74-479f-a908-c8bc91885d44'),
  ('00000061-0000-4000-8000-000000000005', '27a0b547-c58b-4404-b2e9-cf5bb40893d6', '00000021-0000-4000-8000-000000000002', '00000051-0000-4000-8000-000000000002', 'Best and Final (BAFO)', 2, '2025-10-01', 'USD', 1, 3960000, 12, 'final', true, true, now(), 'c9b10017-4a74-479f-a908-c8bc91885d44', now(), 'c9b10017-4a74-479f-a908-c8bc91885d44'),
  ('00000061-0000-4000-8000-000000000006', '27a0b547-c58b-4404-b2e9-cf5bb40893d6', '00000021-0000-4000-8000-000000000003', '00000051-0000-4000-8000-000000000003', 'Initial', 1, '2026-03-01', 'USD', 1, 1100000, 12, 'opening', true, false, now(), 'c9b10017-4a74-479f-a908-c8bc91885d44', now(), 'c9b10017-4a74-479f-a908-c8bc91885d44'),
  ('00000061-0000-4000-8000-000000000007', '27a0b547-c58b-4404-b2e9-cf5bb40893d6', '00000021-0000-4000-8000-000000000003', '00000051-0000-4000-8000-000000000003', 'Best and Final (BAFO)', 2, '2026-03-01', 'USD', 1, 900000, 12, 'final', true, true, now(), 'c9b10017-4a74-479f-a908-c8bc91885d44', now(), 'c9b10017-4a74-479f-a908-c8bc91885d44'),
  ('00000061-0000-4000-8000-000000000008', '27a0b547-c58b-4404-b2e9-cf5bb40893d6', '00000021-0000-4000-8000-000000000004', '00000051-0000-4000-8000-000000000006', 'Initial', 1, '2026-05-01', 'USD', 1, 500000, 12, 'opening', true, false, now(), 'c9b10017-4a74-479f-a908-c8bc91885d44', now(), 'c9b10017-4a74-479f-a908-c8bc91885d44'),
  ('00000061-0000-4000-8000-000000000009', '27a0b547-c58b-4404-b2e9-cf5bb40893d6', '00000021-0000-4000-8000-000000000004', '00000051-0000-4000-8000-000000000006', 'Best and Final (BAFO)', 2, '2026-05-01', 'USD', 1, 425000, 12, 'final', true, true, now(), 'c9b10017-4a74-479f-a908-c8bc91885d44', now(), 'c9b10017-4a74-479f-a908-c8bc91885d44'),
  ('00000061-0000-4000-8000-000000000010', '27a0b547-c58b-4404-b2e9-cf5bb40893d6', '00000021-0000-4000-8000-000000000005', '00000051-0000-4000-8000-000000000006', 'Best and Final (BAFO)', 1, '2026-02-01', 'USD', 1, 540000, 12, 'final', true, true, now(), 'c9b10017-4a74-479f-a908-c8bc91885d44', now(), 'c9b10017-4a74-479f-a908-c8bc91885d44'),
  ('00000061-0000-4000-8000-000000000011', '27a0b547-c58b-4404-b2e9-cf5bb40893d6', '00000021-0000-4000-8000-000000000006', '00000051-0000-4000-8000-000000000005', 'Initial', 1, '2026-09-01', 'USD', 1, 1400000, 12, 'opening', true, false, now(), 'c9b10017-4a74-479f-a908-c8bc91885d44', now(), 'c9b10017-4a74-479f-a908-c8bc91885d44'),
  ('00000061-0000-4000-8000-000000000012', '27a0b547-c58b-4404-b2e9-cf5bb40893d6', '00000021-0000-4000-8000-000000000006', '00000051-0000-4000-8000-000000000005', 'Revised', 2, '2026-09-01', 'USD', 1, 1080000, 12, 'final', true, true, now(), 'c9b10017-4a74-479f-a908-c8bc91885d44', now(), 'c9b10017-4a74-479f-a908-c8bc91885d44'),
  ('00000061-0000-4000-8000-000000000013', '27a0b547-c58b-4404-b2e9-cf5bb40893d6', '00000021-0000-4000-8000-000000000007', '00000051-0000-4000-8000-000000000008', 'Initial', 1, '2026-04-01', 'USD', 1, 11000000, 60, 'opening', true, false, now(), 'c9b10017-4a74-479f-a908-c8bc91885d44', now(), 'c9b10017-4a74-479f-a908-c8bc91885d44'),
  ('00000061-0000-4000-8000-000000000014', '27a0b547-c58b-4404-b2e9-cf5bb40893d6', '00000021-0000-4000-8000-000000000007', '00000051-0000-4000-8000-000000000008', 'Best and Final (BAFO)', 2, '2026-04-01', 'USD', 1, 9000000, 60, 'final', true, true, now(), 'c9b10017-4a74-479f-a908-c8bc91885d44', now(), 'c9b10017-4a74-479f-a908-c8bc91885d44');

-- Savings calculations, DERIVED (whole-term basis) by the same chain the app uses.
insert into public.savings_calculations (id, organization_id, event_id, baseline_id,
  calculation_name, savings_type, baseline_total_amount, opening_proposal_amount,
  award_total_amount, gross_savings_amount, savings_percentage, net_savings_amount,
  cost_reduction_amount, cost_avoidance_amount, calculation_status, recognition_notes,
  savings_start_date, savings_end_date, created_at, created_by, updated_at, updated_by) values
  ('000000a1-0000-4000-8000-000000000001', '27a0b547-c58b-4404-b2e9-cf5bb40893d6', '00000021-0000-4000-8000-000000000001', '00000041-0000-4000-8000-000000000001', 'Whole-term savings', 'Cost Avoidance', 3000000.0, 3600000.0, 2700000, 900000.0, 30.0, 900000.0, 300000.0, 600000.0, 'contracted', 'Derived from the selected anchors over the 36-month term.', '2026-01-01', '2028-12-31', now(), 'c9b10017-4a74-479f-a908-c8bc91885d44', now(), 'c9b10017-4a74-479f-a908-c8bc91885d44'),
  ('000000a1-0000-4000-8000-000000000002', '27a0b547-c58b-4404-b2e9-cf5bb40893d6', '00000021-0000-4000-8000-000000000002', '00000041-0000-4000-8000-000000000002', 'Whole-term savings', 'Cost Reduction', 4500000.0, 4800000.0, 3960000, 840000.0, 18.67, 840000.0, 540000.0, 300000.0, 'realized', 'Derived from the selected anchors over the 12-month term.', '2025-10-01', '2026-09-30', now(), 'c9b10017-4a74-479f-a908-c8bc91885d44', now(), 'c9b10017-4a74-479f-a908-c8bc91885d44'),
  ('000000a1-0000-4000-8000-000000000003', '27a0b547-c58b-4404-b2e9-cf5bb40893d6', '00000021-0000-4000-8000-000000000003', '00000041-0000-4000-8000-000000000003', 'Whole-term savings', 'Cost Avoidance', 800000.0, 1100000.0, 900000, 200000.0, 25.0, 200000.0, -100000.0, 300000.0, 'contracted', 'Derived from the selected anchors over the 12-month term.', '2026-03-01', '2027-02-28', now(), 'c9b10017-4a74-479f-a908-c8bc91885d44', now(), 'c9b10017-4a74-479f-a908-c8bc91885d44'),
  ('000000a1-0000-4000-8000-000000000004', '27a0b547-c58b-4404-b2e9-cf5bb40893d6', '00000021-0000-4000-8000-000000000004', null, 'Whole-term savings', 'Cost Avoidance', null, 500000.0, 425000, 75000.0, 15.0, 75000.0, null, 75000.0, 'contracted', 'Derived from the selected anchors over the 12-month term.', '2026-05-01', '2027-04-30', now(), 'c9b10017-4a74-479f-a908-c8bc91885d44', now(), 'c9b10017-4a74-479f-a908-c8bc91885d44'),
  ('000000a1-0000-4000-8000-000000000005', '27a0b547-c58b-4404-b2e9-cf5bb40893d6', '00000021-0000-4000-8000-000000000005', '00000041-0000-4000-8000-000000000005', 'Whole-term savings', 'Cost Reduction', 600000.0, null, 540000, 60000.0, 10.0, 60000.0, 60000.0, 0.0, 'contracted', 'Derived from the selected anchors over the 12-month term.', '2026-02-01', '2027-01-31', now(), 'c9b10017-4a74-479f-a908-c8bc91885d44', now(), 'c9b10017-4a74-479f-a908-c8bc91885d44'),
  ('000000a1-0000-4000-8000-000000000006', '27a0b547-c58b-4404-b2e9-cf5bb40893d6', '00000021-0000-4000-8000-000000000006', '00000041-0000-4000-8000-000000000006', 'Whole-term savings', 'Cost Avoidance', 1200000.0, 1400000.0, 1080000, 320000.0, 26.67, 320000.0, 120000.0, 200000.0, 'negotiated', 'Derived from the selected anchors over the 12-month term.', '2026-09-01', '2027-08-31', now(), 'c9b10017-4a74-479f-a908-c8bc91885d44', now(), 'c9b10017-4a74-479f-a908-c8bc91885d44'),
  ('000000a1-0000-4000-8000-000000000007', '27a0b547-c58b-4404-b2e9-cf5bb40893d6', '00000021-0000-4000-8000-000000000007', '00000041-0000-4000-8000-000000000007', 'Whole-term savings', 'Cost Reduction', 10000000.0, 11000000.0, 9000000, 2000000.0, 20.0, 2000000.0, 1000000.0, 1000000.0, 'contracted', 'Derived from the selected anchors over the 60-month term.', '2026-04-01', '2031-03-31', now(), 'c9b10017-4a74-479f-a908-c8bc91885d44', now(), 'c9b10017-4a74-479f-a908-c8bc91885d44');

commit;

