import { chainSavings } from '../lib/savings/index.ts'

function sqlNumber(value: number | null): string {
  return value === null ? 'null' : String(value)
}

export function renderChainContractFixture(): string {
  const period = { baseline: 1_000_000, opening: 900_000, final: 900_000 }
  const calculation = { baseline: 3_000_000, opening: 2_700_000, final: 2_700_000 }
  const periodChain = chainSavings(period)
  const calculationChain = chainSavings(calculation)

  return `-- GENERATED by scripts/chain-contract-fixture.ts. Do not hand-edit.
-- The application test verifies this exact file against chainSavings(); pgTAP
-- then submits the generated values to the real database constraints.
begin;

create extension if not exists pgtap with schema extensions;
set local search_path = extensions, public, pg_catalog;

select plan(4);

select lives_ok(
  $$ update public.savings_periods
     set baseline_amount = ${period.baseline},
         opening_amount = ${period.opening},
         final_amount = ${period.final},
         cost_reduction_amount = ${sqlNumber(periodChain.reduction)},
         cost_avoidance_amount = ${periodChain.avoidance},
         total_savings_amount = ${periodChain.total},
         executed_baseline_amount = ${period.baseline},
         executed_opening_amount = ${period.opening},
         executed_final_amount = ${period.final},
         executed_cost_reduction_amount = ${sqlNumber(periodChain.reduction)},
         executed_cost_avoidance_amount = ${periodChain.avoidance},
         executed_total_savings_amount = ${periodChain.total}
     where id = '00000000-0000-4000-8000-000000000061' $$,
  'the database accepts the TypeScript-generated signed period chain'
);

select is(
  (select array[cost_reduction_amount, cost_avoidance_amount, total_savings_amount]
   from public.savings_periods
   where id = '00000000-0000-4000-8000-000000000061'),
  array[${sqlNumber(periodChain.reduction)}, ${periodChain.avoidance}, ${periodChain.total}]::numeric[],
  'the stored period legs equal the TypeScript fixture verbatim'
);

select lives_ok(
  $$ update public.savings_calculations
     set baseline_total_amount = ${calculation.baseline},
         opening_proposal_amount = ${calculation.opening},
         award_total_amount = ${calculation.final},
         cost_reduction_amount = ${sqlNumber(calculationChain.reduction)},
         cost_avoidance_amount = ${calculationChain.avoidance},
         gross_savings_amount = ${calculationChain.total},
         net_savings_amount = ${calculationChain.total}
     where id = '00000000-0000-4000-8000-000000000051' $$,
  'the database accepts the TypeScript-generated signed calculation chain'
);

select is(
  (select array[cost_reduction_amount, cost_avoidance_amount, gross_savings_amount]
   from public.savings_calculations
   where id = '00000000-0000-4000-8000-000000000051'),
  array[${sqlNumber(calculationChain.reduction)}, ${calculationChain.avoidance}, ${calculationChain.total}]::numeric[],
  'the stored calculation legs equal the TypeScript fixture verbatim'
);

select * from finish();
rollback;
`
}
